spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:architectBudgePlannerApplication
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  spring.flyway.locations: db